name: "Docs Build"

on:
  pull_request_target:
    types:
      - opened

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/_build/html/
